name: auto-update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "30 08 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update
        run: |
          wget https://github.com/absxsfriends/scoop-bucket/releases/download/v0.1.0/auto-update-linux.tar.gz -O /tmp/au.tar.gz
          tar -xzf /tmp/au.tar.gz -C /tmp
          chmod +x /tmp/auto-update
          /tmp/auto-update bucket
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
