name: auto-update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "30 08 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update
        run: ./update.sh
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
